# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer0.dell.mazen.com:
  peer1.dell.mazen.com:

networks:
  byfn:

services:

  peer0.dell.mazen.com:
    container_name: peer0.dell.mazen.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.dell.mazen.com
      - CORE_PEER_ADDRESS=peer0.dell.mazen.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.dell.mazen.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.dell.mazen.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dell.mazen.com:11051
      - CORE_PEER_LOCALMSPID=dellMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./dell-artifacts/crypto-config/peerOrganizations/dell.mazen.com/peers/peer0.dell.mazen.com/msp:/etc/hyperledger/fabric/msp
        - ./dell-artifacts/crypto-config/peerOrganizations/dell.mazen.com/peers/peer0.dell.mazen.com/tls:/etc/hyperledger/fabric/tls
        - peer0.dell.mazen.com:/var/hyperledger/production
    ports:
      - 11051:11051
    networks:
      - byfn

  peer1.dell.mazen.com:
    container_name: peer1.dell.mazen.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.dell.mazen.com
      - CORE_PEER_ADDRESS=peer1.dell.mazen.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.dell.mazen.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.dell.mazen.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.dell.mazen.com:12051
      - CORE_PEER_LOCALMSPID=dellMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./dell-artifacts/crypto-config/peerOrganizations/dell.mazen.com/peers/peer1.dell.mazen.com/msp:/etc/hyperledger/fabric/msp
        - ./dell-artifacts/crypto-config/peerOrganizations/dell.mazen.com/peers/peer1.dell.mazen.com/tls:/etc/hyperledger/fabric/tls
        - peer1.dell.mazen.com:/var/hyperledger/production
    ports:
      - 12051:12051
    networks:
      - byfn


  dellcli:
    container_name: dellcli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=dellcli
      - CORE_PEER_ADDRESS=peer0.dell.mazen.com:11051
      - CORE_PEER_LOCALMSPID=dellMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dell.mazen.com/peers/peer0.dell.mazen.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dell.mazen.com/peers/peer0.dell.mazen.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dell.mazen.com/peers/peer0.dell.mazen.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/dell.mazen.com/users/Admin@dell.mazen.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./dell-artifacts/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./crypto-config/peerOrganizations/microsoft.mazen.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/microsoft.mazen.com
        - ./crypto-config/peerOrganizations/oracle.mazen.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/oracle.mazen.com
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.dell.mazen.com
      - peer1.dell.mazen.com
    networks:
      - byfn
