# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer2.mazen.com:
  orderer3.mazen.com:
  orderer4.mazen.com:
  orderer5.mazen.com:

networks:
  byfn:

services:

  orderer2.mazen.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer2.mazen.com
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/mazen.com/orderers/orderer2.mazen.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/mazen.com/orderers/orderer2.mazen.com/tls/:/var/hyperledger/orderer/tls
        - orderer2.mazen.com:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.mazen.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer3.mazen.com
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/mazen.com/orderers/orderer3.mazen.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/mazen.com/orderers/orderer3.mazen.com/tls/:/var/hyperledger/orderer/tls
        - orderer3.mazen.com:/var/hyperledger/production/orderer
    ports:
    - 9050:7050

  orderer4.mazen.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer4.mazen.com
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/mazen.com/orderers/orderer4.mazen.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/mazen.com/orderers/orderer4.mazen.com/tls/:/var/hyperledger/orderer/tls
        - orderer4.mazen.com:/var/hyperledger/production/orderer
    ports:
    - 10050:7050

  orderer5.mazen.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer5.mazen.com
    networks:
    - byfn
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/mazen.com/orderers/orderer5.mazen.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/mazen.com/orderers/orderer5.mazen.com/tls/:/var/hyperledger/orderer/tls
        - orderer5.mazen.com:/var/hyperledger/production/orderer
    ports:
    - 11050:7050
